spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/users
    driver-class-name: org.postgresql.Driver
    username: user
    password: secret

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


app:
  webauthn:
    rp-id: localhost
    rp-name: Frostbyte User Service
    allowed-origins:
      - http://localhost:8000
      - http://localhost:8080
      - http://user-service:8000
server:
  port: 8000
