spring:
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create-drop


  docker:
    compose:
      enabled: false

  config:
    activate:
      on-profile: local

server:
  port: 8001


app:
  webauthn:
    rp-id: localhost
    rp-name: Frostbyte User Service
    allowed-origins:
      - http://localhost:8000
      - http://localhost:8001